/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class d_hl_andbdiff_BDiffUtil */

#ifndef _Included_d_hl_andbdiff_BDiffUtil
#define _Included_d_hl_andbdiff_BDiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     d_hl_andbdiff_BDiffUtil
 * Method:    applyDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_d_hl_andbdiff_BDiffUtil_applyDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     d_hl_andbdiff_BDiffUtil
 * Method:    applyPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_d_hl_andbdiff_BDiffUtil_applyPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
